INSERT INTO [Shops] (  [Name],              [CountryId]  )
			VALUES  (   N'Big Book Shop',        1       ),
			        (   N'Books',                1       ),
					(   N'Книжный Рай',          2       ),
					(   N'Энциклопедия книг',    3       ),
					(   N'Книжный',              2       ),
					(   N'Libreria',             7       ),
					(   N'Grande libreria',      7       ),
					(   N'Gran librería',        10      ),
					(   N'Libro paraíso',        10      ),
					(   N'Книжный Домик',        3       ),
					(   N'Book Boom',            1       ),
					(   N'Buchboom',             5       ),
					(   N'Entrepôt de livres',   6       ),
					(   N'Paradis du livre',     6       )